### PR TITLE
Feat update readme

### PR DESCRIPTION
**Pull request by ChinmayShringi**
Fixes # (issue)

### Changes Summary
Updated Readme file added step-by-step guide to access the NYU SSH server and run Docker commands to set up and test the Lind project with rawPOSIX.
- **Change A**: Updated network verification steps in `SSH Access Guide`.
- **Change B**: Added Docker container setup instructions to the documentation.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary documentation for new and modified methods.
- [x] I have attached screenshots for visual changes (if applicable).
- [x] My changes generate no new warnings or errors.
- [x] I have added unit/integration tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (`native-client`, `lind-glibc`, `lind-project`).

### CODE REVIEW

**Review by Yaxuan-w — APPROVED** [review]
That looks great!! Great job!

**Review by yzhang71 — APPROVED** [review]
LGTM, this is very useful!

**Comment by rennergade** [comment]
I agree that this looks great and is awesome. I think it makes more sense to put in the lind-docs repo than here though.

**Comment by Yaxuan-w** [comment]
> I agree that this looks great and is awesome. I think it makes more sense to put in the lind-docs repo than here though.

I think we can do both since current RawPOSIX repo also needs modification and this could be a good start

**Pull request merged**
