### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yashaswi2000**

### CODE REVIEW

**Comment by rennergade** [comment]
@Yaxuan-w Can you check if this commit history is up to date? @qianxichen233 are these the commits you need?

**Comment by Yaxuan-w** [comment]
> @Yaxuan-w Can you check if this commit history is up to date? @qianxichen233 are these the commits you need?

Do we need to integrate in memory pipes as well?

**Comment by rennergade** [comment]
> > @Yaxuan-w Can you check if this commit history is up to date? @qianxichen233 are these the commits you need?
> 
> Do we need to integrate in memory pipes as well?

No, we'll leave that out of this. We at least need it to be in the last working state. Though we should probably add the test suite and Justin's more recent fdtables updates. I'm not sure at what state this is at.

**Review by Yaxuan-w — CHANGES_REQUESTED** [review]
I think the current `develop` branch is almost same with older rustposix, which is the initial version. The most up-to-date version should be `alice` branch.

I noticed that the most import thing for this PR should be GitHub workflow and some PR template setups, so maybe we could first merge this pr to `main` / first merge `alice` into this branch. Either works for me.

**Comment by rennergade** [comment]
lets change this to add the "alice" branch as main, and also squash commits

**Pull request closed without merging**
